### ISSUE TITLE
Table item height

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#10]
current item height is 48px

the correct itemheight should be **40px**

![image](https://user-images.githubusercontent.com/2656996/34817885-846832ec-f6b9-11e7-9faa-ca751f55d276.png)

**Comment by andwah** [comment]
I updated the table border posistion.. it was moved up by 2px, the text inside and titles remains where they are.

Red is correct border posision in this image below, i put the current design as an overlay.

![image](https://user-images.githubusercontent.com/2656996/35501659-da8b47a2-04da-11e8-9e1e-f92a36e8d82c.png)

**Comment by alshakero** [comment]
Updated.

**Comment by andwah** [comment]
almost, but the items are now 39px height, it should be 40px.

Here is a pic, redlines is the correct layout, 

![image](https://user-images.githubusercontent.com/2656996/35513648-158ef6a4-0504-11e8-860a-daf8d16e27ec.png)

**Comment by andwah** [comment]
and the text is now a bit off to in y-axis

**Comment by andwah** [comment]
Here is the template

![image](https://user-images.githubusercontent.com/2656996/35513730-421ec280-0504-11e8-9e76-77b2138e045c.png)

**Comment by alshakero** [comment]
Updated. Here is how it looks now
![image](https://user-images.githubusercontent.com/17054134/35514384-4cd228fa-0506-11e8-88a2-d10377f7c933.png)

**Comment by andwah** [comment]
Just checked latest code, Item height is now perfect
But.. all lines should be moved up 1px, or all text moved down 1px

also take a quick look at the corner radius.. it should have same values as buttons an all other components. (2px)

**Comment by andwah** [comment]
![image](https://user-images.githubusercontent.com/2656996/35514897-fa4d7628-0507-11e8-896a-930bd0fec0d8.png)

**Comment by alshakero** [comment]
Good to go?

**Comment by andwah** [comment]
border and text position is excellent!.
just add the corner-radius then you can close this.

**Comment by alshakero** [comment]
![image](https://user-images.githubusercontent.com/17054134/35519499-b98d9aa2-0514-11e8-92a6-d7db525f476c.png)

I think it's already 2px?

**Comment by andwah** [comment]
your right!.
