### ISSUE TITLE
Checkbox issues

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#11]
Current view:
![image](https://user-images.githubusercontent.com/2656996/34818082-157cf790-f6ba-11e7-844a-0a1dbdd712e9.png)

Correct view:
![image](https://user-images.githubusercontent.com/2656996/34818075-0fec7d28-f6ba-11e7-8145-dd2e7cf7f907.png)

![image](https://user-images.githubusercontent.com/2656996/34818226-8153e46a-f6ba-11e7-9f73-35af0dc490d0.png)

- [ ] Checkmack image: check-noun_1325224.svg
- [ ] Checkmark image size: w:10px h: adjustable (but it's around 11,51px)
- [ ] Box size w:24 h:24
- [ ] Box border color: #DFDFDF
- [ ] Box border width: 1px

**Comment by alshakero** [comment]
I enhanced this a bit. Is it closable now?
