### ISSUE TITLE
Expand the demo page

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#15]
Expand the demo page to include all form elements, headers and other kinds of typography. Take inspiration from Miligram and Sakura demo pages.

**Comment by alshakero** [comment]
I think this is done now right? https://starcounter.github.io/underwear.css/

**Comment by warpech** [comment]
I can still some things that are presented on [Sakura demo page](https://oxal.org/projects/sakura/demo/) that are not in our demo:

- `<code>` should be showed mixed with text.
- horizontal line is not presented
- table caption should be presented
- `<img>` is not presented
- `<fieldset> is not presented
- input type `radio` is not presented
- textarea is not presented
- input type `button`, `submit`, `reset` is not presented

Feel free to do this in one PR or to split into separate issues.

**Comment by alshakero** [comment]
Great ideas. I will create one PR.

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/underwear.css/pull/29

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/underwear.css/pull/29
