### ISSUE TITLE
Button text one pixel off,

### ISSUE THREAD

**Issue by andwah** [Starcounter/underwear.css#16]
The text inside the button should be 1 pixel lower

![image](https://user-images.githubusercontent.com/2656996/35500816-071f007c-04d8-11e8-960c-77bdfb9a6a72.png)

**Comment by alshakero** [comment]
Updated.

**Comment by andwah** [comment]
Button text is off by 1px

![image](https://user-images.githubusercontent.com/2656996/36471414-a4288726-16ee-11e8-826b-f6c85f39d437.png)
Red is the desired design

**Comment by warpech** [comment]
I am moving this to Q2. I think that the only sustainable to do such fixes is if @andwah makes such adjustments directly in the CSS and makes a PR to Underwear.css and Uniform.css.

**Comment by warpech** [comment]
Issue moved to [Starcounter/uniform.css #149](https://github.com/Starcounter/uniform.css/issues/149) via [**ZenHub**](https://www.zenhub.com/)
