### ISSUE TITLE
Wrong Entryfield height

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#17]
Current height is 32px, should be 38px

![image](https://user-images.githubusercontent.com/2656996/35501883-8a343d62-04db-11e8-9310-24fcb9e05415.png)

Correct

![image](https://user-images.githubusercontent.com/2656996/35501912-9fb0c30e-04db-11e8-82a9-16db5b6c0d68.png)

**Comment by alshakero** [comment]
Updated (Changes are in https://github.com/Starcounter/Underwear.css/tree/reviewable-branch)
