### ISSUE TITLE
Margin 0 should be removed from underwear

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#24]
During work on new layout for blending app I found out that underwear.css sets margin: 0 for body:

![image](https://user-images.githubusercontent.com/25042256/35965903-8ecf53a0-0cbc-11e8-9be8-b116b303f019.png)

It comes from normalize.css and should be removed/overwritten due to negative margin set by composition (https://github.com/Starcounter/Home/issues/107#issuecomment-360778911)

**Comment by warpech** [comment]
> It comes from normalize.css and should be removed/overwritten due to negative margin set by composition (Starcounter/Home#107 (comment))

This is not the reason for this request.

The reason for this request is to remove opinionated reset included in Normalize.css that sets the `body` margin to 0. Underwear.css should follow more canonic behavior of having the 8px margin in `body`, as recommended by the CSS spec: https://www.w3.org/TR/CSS2/sample.html

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/underwear.css/pull/25
