### ISSUE TITLE
Checkbox styled by underwear doesn't match our design

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#26]
Current checkbox styled by underwear:
![image](https://user-images.githubusercontent.com/25042256/35978216-654c7dea-0ce5-11e8-8aad-271f836b614e.png)
checkbox in design:
![image](https://user-images.githubusercontent.com/25042256/35978239-74c405f4-0ce5-11e8-822f-28ad395a6981.png)

**Comment by andwah** [comment]
see https://github.com/Starcounter/underwear.css/issues/11

**Comment by warpech** [comment]
It isn't without reason that the two most popular CSS frameworks in the world leave checkbox and radio unstyled:

- http://getbootstrap.com/docs/4.0/components/forms/
- https://foundation.zurb.com/sites/docs/forms.html

@andwah would it be awful to follow that example?

**Comment by PatrykSzwer** [comment]
TBH default checkboxes in our default designs would look awful and out of place. Do You think it would be possible to style this with uniform? Or CE?

**Comment by andwah** [comment]
> would it be awful to follow that example? Right now we have a checkbox that is neither custom styled nor default, which looks kind of weird to me.

Not sure that i undertstand the question. I dont know the technical part so well.

**Comment by alshakero** [comment]
> Do You think it would be possible to style this with uniform

Not really. You'd need to have a label next to the checkbox to be able to style it in a way that works everywhere.

> CE

Sure, it's possible but I don't think it would have anything to do with our CSS then. 

I say we should just remove the non-default sizing and stick to normal checkboxes.

**Comment by warpech** [comment]
Right now the checkbox has a default look and custom size. It does not look consistent in all browsers.

## How it looks right now (MacOs: Firefox, Chrome, Safari)

<img width="1440" alt="screen shot 2018-02-09 at 11 12 32" src="https://user-images.githubusercontent.com/566463/36022993-38b8140a-0d8b-11e8-9205-98e5f05c573c.png">

## How it looks right now (Windows: Firefox, Chrome, Edge)

![2018-02-09 11_16_03-greenshot](https://user-images.githubusercontent.com/566463/36023003-42906ed2-0d8b-11e8-8192-cb24935203da.png)

## How it will look after we use the default size (MacOs: Firefox, Chrome, Safari)

<img width="1440" alt="screen shot 2018-02-09 at 11 19 43" src="https://user-images.githubusercontent.com/566463/36023018-500df4bc-0d8b-11e8-80a9-028d32efc790.png">

## How it will look after we use the default size (Windows: Firefox, Chrome, Edge)

![2018-02-09 11_18_14-greenshot](https://user-images.githubusercontent.com/566463/36023036-5cb16f50-0d8b-11e8-98ff-a7b66cee5581.png)

--------

Given that we are not able:

- have a custom SVG look and feel without hackery that is too heavy (see: #11)
- have a custom size of a default checkbox in all browsers (see above screenshots)

> I say we should just remove the non-default sizing and stick to normal checkboxes.

This is my recommendation, too. Let's do this and perhaps revise checkboxes in Q2. @andwah do you agree?

**Comment by andwah** [comment]
> I say we should just remove the non-default sizing and stick to normal checkboxes.

Also agree, but i dont like it :-)

**Comment by warpech** [comment]
Thanks guys! To wrap up:

- revert custom sizing of a checkbox in Underwear.css
- in future, implement the nice SVG solution in Uniform.css (https://github.com/Starcounter/uniform.css/issues/24)

The last point should be a good news for you @andwah  :)

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/underwear.css/pull/29
