### ISSUE TITLE
Horizantal line is barely visible

### ISSUE THREAD

**Issue by alshakero** [Starcounter/underwear.css#28]
![image](https://user-images.githubusercontent.com/17054134/36026475-882bf734-0d97-11e8-8a0b-726e1d87154a.png)

I made it thicker and darker, is this OK @andwah?

**Comment by andwah** [comment]
did you use #E7E7E7 for the new "darker" color?

**Comment by alshakero** [comment]
I used `--light-gray` which is #E1E1E1.

**Comment by alshakero** [comment]
Changed to #E7 and it's much nicer, you're right

![image](https://user-images.githubusercontent.com/17054134/36036805-16940f34-0dbb-11e8-8d98-011c4581c411.png)

**Comment by andwah** [comment]
> You can see it live here https://rawgit.com/Starcounter/underwear.css/Enhancements/index.html

It seems that the "Button" font on that page is not using "Roboto", looks like it's Sans Serif..

**Comment by alshakero** [comment]
Closing as fixed in https://github.com/Starcounter/underwear.css/pull/29
