### ISSUE TITLE
Button shadow adjustment.

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#3]
Try with this shadow values on the button

**box-shadow: 0px 1px 3px 0 rgba(0,0,0,.20);**

before:
![image](https://user-images.githubusercontent.com/2656996/34784100-9d0fb522-f62d-11e7-95e4-4f1cf1b32396.png)

after:
![image](https://user-images.githubusercontent.com/2656996/34784084-949e3030-f62d-11e7-897f-22d9b222aad4.png)

**Comment by andwah** [comment]
Still needs some adjustment, see image

![image](https://user-images.githubusercontent.com/2656996/35500865-41b4958a-04d8-11e8-90ac-6fed24dd9ca0.png)

I used the same value as i use im Adobe XD tool fo the box-shadow values. maybe the browser and this tool dosent use the same formulas?.

**Comment by alshakero** [comment]
Apparently. I use exactly the same values. I'll cheat a little.

**Comment by andwah** [comment]
Left = Template, Right = underware.css

![image](https://user-images.githubusercontent.com/2656996/35514615-1102f100-0507-11e8-930a-a35fab42e9a6.png)

Looks good for me.

**Comment by alshakero** [comment]
_Reponed after Slack conversation_

I don't know but isn't this the same? And btw, it might be better to zoom in the browser before you take the screenshot rather than in the editor.

![image](https://user-images.githubusercontent.com/17054134/35515597-f15d741c-0509-11e8-9d5b-fa0200781d30.png)

**Comment by andwah** [comment]
look very alike :-)
