### ISSUE TITLE
Wrong font in button.

### ISSUE THREAD

**Issue by andwah** [Starcounter/underwear.css#38]
Button font should be Roboto Regular 14px

**Comment by warpech** [comment]
Moved from https://github.com/Starcounter/underwear.css/issues/38:

----

![image](https://user-images.githubusercontent.com/2656996/36099302-721cf444-1002-11e8-9227-1bb4148bb520.png)

The font should be "Roboto" Regular

**Comment by alshakero** [comment]
Yes this should be fixed in #40
