### ISSUE TITLE
Demo page has plenty of validation errors

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#41]
`index.html` has so many validation errors that https://validator.w3.org/nu/#textarea gives up after the 15th error. Please try to reduce the number of errors such as unclosed tags.

**Comment by alshakero** [comment]
Fixed in https://github.com/Starcounter/underwear.css/commit/dbb223c0d14f63613adfc3d2466eb29e54123bcb.

**Comment by warpech** [comment]
Closing as done
