### ISSUE TITLE
The color palette is uneven

### ISSUE THREAD

**Issue by warpech** [Starcounter/underwear.css#43]
There are many similar very light shades of gray in the color palette. 

There should be just a few (max 5), evenly distributed shades of gray from very light to very dark.

Perhaps, there should also be the same number of shades of "bluish gray".

Interactive effects on buttons (`hover`, `active`, `focused`, `disabled`) should be done using CSS filters, to unpollute the color palette.

Compare with color palettes of:

- Bootstrap -[source](https://github.com/twbs/bootstrap/blob/f81f419b22949d2bf0f4d346891be44724109135/scss/_variables.scss), [demo](https://getbootstrap.com/docs/4.0/getting-started/theming/#color)
- Bulma - [source](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass), [demo](https://bulma.io/documentation/overview/colors/)
- MCW - [source](https://github.com/material-components/material-components-web/blob/9bb3be544b5b2390e7a7ab31cf40047028494e20/packages/mdc-theme/_color-palette.scss#L270-L279), [demo](https://material.io/guidelines/style/color.html#color-color-palette)

**Comment by andwah** [comment]
i will see if i can simplify that.  
btw is it okey to use black with transparency to get same color effect?

**Comment by warpech** [comment]
Opacity in CSS works as layer opacity in Photoshop with blend mode `normal`. It might need to undesired results, because this way you will not be able to have something like real gray on yellow background.

Opacity is also some hit on performance, but nowadays all devices have GPUs that should handle it good enough.

I examined a few of CSS frameworks and they don't have transparent colors.

**Comment by andwah** [comment]
I grouped the palette into this:

![image](https://user-images.githubusercontent.com/2656996/36739823-31b6951e-1be1-11e8-81d2-dc7ec6c0b9df.png)

**Comment by warpech** [comment]
Closing as won't fix. We will use the color palette of Lumo but adapt to @andwah's colors where appropriate. This is tracked in https://github.com/Starcounter/uniform.css/issues/121
