### ISSUE TITLE
Typo in button-background-color variable

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#46]
--while? I believe you meant white.

![image](https://user-images.githubusercontent.com/25042256/36376332-0bd77440-1573-11e8-9df4-6a6ae40aff05.png)

**Comment by alshakero** [comment]
This is fixed in https://github.com/Starcounter/underwear.css/releases/tag/0.0.3

**Comment by warpech** [comment]
Closing as won't fix (already fixed)
