### ISSUE TITLE
Dropdown wrong "icon" and shadow values

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#5]
How it should look like:
![image](https://user-images.githubusercontent.com/2656996/34816806-50ffa960-f6b6-11e7-8827-c4f7c84d4007.png)

Current:

![image](https://user-images.githubusercontent.com/2656996/34816817-5915e29a-f6b6-11e7-9f76-c97651b6db13.png)

The image to use is "dropdown_1270376.svg"

**Comment by alshakero** [comment]
Is this closable?
