### ISSUE TITLE
Disabled select field has no arrow

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/underwear.css#55]
I see almost no difference between button and dropdown that is disabled:

![underwear_css](https://user-images.githubusercontent.com/4943949/36527593-9ca72858-17b2-11e8-990e-460ff2379079.png)

There should be an arrow on the right (as in enabled dropdown) to make it intuitive and distinguishable from the button.

**Comment by PatrykSzwer** [comment]
Closing as done.
