### ISSUE TITLE
Table has some unexpected second border

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#57]
![table](https://user-images.githubusercontent.com/25042256/36591434-4c7991f0-1892-11e8-9dfa-d3b3bddc5719.png)

Reported by @joltrix

**Comment by warpech** [comment]
How to reproduce this? I can't reproduce it on the [demo page](https://starcounter.github.io/underwear.css/).

**Comment by warpech** [comment]
The problem of the cell background color should be fixed by: https://github.com/Starcounter/underwear.css/pull/60

**Comment by Joltrix** [comment]
I think this was a result of some styling still remaining from before me adding underwear.css

**Comment by warpech** [comment]
Closing as not reproducible then. Please reopen if you have some new evidence :)
