### ISSUE TITLE
Select has different sizing than buttons

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/underwear.css#58]
![select](https://user-images.githubusercontent.com/25042256/36591601-d04ed4d6-1892-11e8-8aa7-dd91686c1b92.png)

It's caused by `box-sizing: inherit`.

Reported by @joltrix

**Comment by warpech** [comment]
How to reproduce it?

On the [demo page](https://starcounter.github.io/underwear.css/), both elements have the same height of 32px:

![image](https://user-images.githubusercontent.com/566463/36736462-f49011b8-1bd8-11e8-8775-ef55949124d0.png)

**Comment by warpech** [comment]
Ok, I know now. It can be reproduced by setting `box-sizing: content-box;` on the container.

**Comment by warpech** [comment]
Fix in PR #61

**Comment by warpech** [comment]
Closing as done
