### ISSUE TITLE
Border in table is not applied to last <td> if its inside a dom-if

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/underwear.css#63]
A table with a dom-if as the last element:

![image](https://user-images.githubusercontent.com/10708580/36779318-e511075a-1c6f-11e8-9066-12815f0ed2ae.png)
![image](https://user-images.githubusercontent.com/10708580/36779320-e8137604-1c6f-11e8-83a6-ccda220a298f.png)

A table without a dom-if as the last element:
![image](https://user-images.githubusercontent.com/10708580/36779339-fea1b16a-1c6f-11e8-98c7-6a2f31d53954.png)
![image](https://user-images.githubusercontent.com/10708580/36779344-024f2478-1c70-11e8-9444-e226c0769b3e.png)

Is this intended? Or can this be fixed :)?

cc @PatrykSzwer

**Comment by warpech** [comment]
Thanks, @Joltrix for a great explanation. I made a PR #66 to fix that. It should be released to Starcounter by Monday EOD.

**Comment by warpech** [comment]
Closing as done. Will be released in Underwear.css 0.0.7
