### ISSUE TITLE
Dropdown items

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#7]
Current view:
![image](https://user-images.githubusercontent.com/2656996/34817221-a37f1d0a-f6b7-11e7-972e-21e4aa3e68c8.png)

Correct view:
![image](https://user-images.githubusercontent.com/2656996/34817231-b61ea3e0-f6b7-11e7-98ec-0a8a32471e9b.png)

- [x] Button color should be #F9F9F9 when the dropdown list is open
- [ ] Missing Item paddin
- [ ] Missing boxshadow in dropdown list ( x:0 y:3 blur:6. 16% black)

**Comment by andwah** [comment]
Magin between the border and the arrow should be 16px, and the shdow is to strong.

The shadow valus is the same on all components exept popup things.

![image](https://user-images.githubusercontent.com/2656996/35502111-2fd62b36-04dc-11e8-9933-b68d1427db8e.png)

**Comment by alshakero** [comment]
Better now?

**Comment by andwah** [comment]
yes. but now the height changed to 38px. and it should be 32px.

**Comment by alshakero** [comment]
![bug](https://media.giphy.com/media/11ZSwQNWba4YF2/source.gif)

**Comment by alshakero** [comment]
Updated.

**Comment by andwah** [comment]
Perfect 🥇
