### ISSUE TITLE
Give html, body and first sc-include 100% height

### ISSUE THREAD

**Issue by alshakero** [Starcounter/underwear.css#73]
I think this isn't very nice
![image](https://user-images.githubusercontent.com/17054134/39046139-6fa3db0c-4495-11e8-8979-2bb516f78118.png)

Giving html, body and first sc-include 100% height would fix this issue.

WDYT @tomalec, @warpech and @PatrykSzwer

**Comment by warpech** [comment]
Certainly, we shouldn't make Underwear.css aware of `starcounter-include`. That would violate the separation of concerns.

On the other hand, I can't think of anything wrong with setting `height: 100%; box-sizing: border-box` on `html` and `body` in Underwear.css.

@Starcounter/webplatformteam can anyone think of a reason to NOT do that?

Then it should be easier to avoid this problem from a composition of the `starcounter-include`.
