### ISSUE TITLE
Styles for date and time input are missing

### ISSUE THREAD

**Issue by miyconst** [Starcounter/underwear.css#77]
It would be nice to have the `<input type="date" />` and `<input type="time" />` also styled [here](https://github.com/Starcounter/underwear.css/blob/master/src/underwear.css#L238).

**Comment by warpech** [comment]
Closing as partially implemented, partially tracked elsewhere.

Date picker is already implemented as a custom element that decorates `<input type="date">:

- docs: https://uniform.starcounter.io/UniformDocs/Datepicker
- temporary more docs: https://github.com/Starcounter/uniform.css/blob/master/components/uni-date-picker/README.md
- temporary more demos: https://starcounter.github.io/uniform.css/components/uni-date-picker/

The benefits of this approach are described in https://github.com/Starcounter/uniform.css/blob/master/components/README.md

The look of `<uni-date-picker>` should be aligned with the look of other components designed by @andwah. This was not done yet.

---

Regarding the time picker, I've created an issue: https://github.com/Starcounter/uniform.css/issues/147

**Comment by miyconst** [comment]
@warpech I don't see why the native browser elements `<input type="date" />` and `<input type="time" />` should be left without styles.

In my case I have a date box, which is not a `uni-date-picker`, and I can't make it be such, because it's nested within other elements. Still, I want consistent look of all the `<input />` elements on the form.

Is not it making sense?
