### ISSUE TITLE
Entryfield background color

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#8]
Current view:

![image](https://user-images.githubusercontent.com/2656996/34817497-74aa7e56-f6b8-11e7-86fa-011d78ce6443.png)
Wrong background color: #EEEEEE

Correct view:
![image](https://user-images.githubusercontent.com/2656996/34817472-63ee09b6-f6b8-11e7-99f9-c94a6ef10355.png)

correct background color: **#F6F6F6**

**Comment by alshakero** [comment]
This is closable now right?
