### ISSUE TITLE
Add Title Example to the entryfield

### ISSUE THREAD

**Issue by andwah** [Starcounter/Underwear.css#9]
Add a Entryfield with an title on the Demo-Page

![image](https://user-images.githubusercontent.com/2656996/34817638-c1cda852-f6b8-11e7-9e47-f91e36b7e651.png)

**Comment by alshakero** [comment]
Updated.

**Comment by andwah** [comment]
Almost perfect, just move down the title 1px

![image](https://user-images.githubusercontent.com/2656996/35520536-98771c0a-0517-11e8-94b0-787438e0fa69.png)

**Comment by alshakero** [comment]
Better?

**Comment by andwah** [comment]
done! 👍
